### ISSUE TITLE
Rest framework 3.0

### ISSUE THREAD

**Issue by 23doors** [djangonauts/django-rest-framework-hstore#4]
Now that 3.0 was released, any plans to support it? It breaks some code at this point.

**Comment by nemesisdesign** [comment]
Released 1.2:

 * git tag: https://github.com/djangonauts/django-rest-framework-hstore/releases/tag/1.2
 * pypi release: https://pypi.python.org/pypi/djangorestframework-hstore/1.2

Many thanks to @jannon!
