### ISSUE TITLE
Support for DRF 3.2.X?

### ISSUE THREAD

**Issue by hvdklauw** [djangonauts/django-rest-framework-hstore#8]
Can you do a build on travis to see if everything will work?

**Comment by nemesisdesign** [comment]
@hvdklauw it works, see here: https://travis-ci.org/djangonauts/django-rest-framework-hstore/builds/68712390
drf-hstore depends on drf>=3.1.1, so each time is installed it will automatically download the latest drf version.
See https://github.com/djangonauts/django-rest-framework-hstore/blob/master/requirements.txt#L3

**Comment by hvdklauw** [comment]
Awesome, thanks!
